apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: stakater-push-main-tag
  annotations:
    description: |
      Push Tag in case of main branch
spec:
  workspaces:
    - name: source
  params:
    - description: Reference of the image tag
      name: IMAGE_TAG
      type: string
    - name: PR_NUMBER
      description: In case of PR, PR number that is to be used in image tag. If this field is empty it means that it's a commit on main branch
      default: "NA"
    - name: GIT_REVISION
      description: The git revision
    - name: PROTOCOL
      description: The protocol that should be used to push changes to the repository
      default: "https"
    - name: GITHUB_TOKEN_SECRET
      description: Name of the secret containing token for the application repo
  steps:
    - name: push-main-tag
      image: stakater/pipeline-toolbox:v0.0.20
      command: ["/bin/bash"]
      workingDir: $(workspaces.source.path)
      env:
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: github-stakater-tekton-bot
              key: password
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-stakater-tekton-bot
              key: username
        - name: GIT_EMAIL
          valueFrom:
            secretKeyRef:
              name: github-stakater-tekton-bot
              key: email
        - name: APPLICATION_REPO_SSH_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.GITHUB_TOKEN_SECRET)
              key: token
      args:
        - -c
        - |
          if [ $(params.PR_NUMBER) == "NA" ] && ( [ $(params.GIT_REVISION) == "main" ] || [ $(params.GIT_REVISION) == "master" ] ); then
            if [ $params.PROTOCOL == "https" ]; then
              git config --global user.name $GIT_USERNAME
              git config --global user.email $GIT_EMAIL
              git config --global user.password $GIT_PASSWORD
            else
              git config --global user.name tekton-bot
              git config --global user.email stakater-tekton-bot@stakater.com
              mkdir ~/.ssh
              ls -a ~/
              > ~/.ssh/id_rsa
              > ~/.ssh/known_hosts
              ls -a ~/.ssh
              echo $APPlICATION_REPO_SSH_TOKEN >> ~/.ssh/id_rsa
              eval `ssh-agent -s`
              ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
              chmod 600  ~/.ssh/id_rsa
              ssh-add ~/.ssh/id_rsa
            fi
              git tag -am "Bump version to $(params.IMAGE_TAG)" $(params.IMAGE_TAG)
              git push --tags
          fi