apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
    name: {{ include "checkov-scan.name" . }}
spec:
  workspaces:
    - name: source
  params:
    - name: BUILD_IMAGE
      description: Flag specifying whether image should be built again.
      default: 'true'
      type: string
  steps:
    - name: scan
      image: bridgecrew/checkov:2
      workingDir: $(workspaces.source.path)
      script: |
        if [[ $(params.BUILD_IMAGE) == true ]]; then
          checkov -d . -s
        fi