apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: {{ include "stakater-comment-on-pr.name" . }}
spec:
  workspaces:
    - name: source
  params:
    - name: image
      description: Reference of the image buildah will produce.
      type: string
    - name: pr-number
      description: In case of PR, PR number that is to be used in image tag. If this field is empty it means that it's a commit on main branch
      default: "NA"
    - name: git-repository-url
      description: The git repository url
  steps:
    - name: comment-on-pr
      image: stakater/pipeline-toolbox:v0.0.20
      command: ["/bin/bash"]
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: "github-tekton-bot"
              key: password
      args:
        - -c
        - |
          if [ $(params.pr-number) != "NA" ]; then
            REPO_URL=$(params.git-repository-url)
            REPO_NAME=${REPO_URL#*$".com"} 
            REPO_NAME=${REPO_NAME:1}
            curl -s -H "Authorization: token ${GITHUBTOKEN}" \
            -X POST -d '{"body": "Tekton - Pipeline ran successfully and image `$(params.image)` is available"}' \
            "https://api.github.com/repos/${REPO_NAME}/issues/$(params.pr-number)/comments"
          else
            echo "Not a PR so cant comment"
          fi
