apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: {{ include "stakater-comment-on-repo.name" . }}
spec:
  workspaces:
    - name: source
  params:
    - description: Reference of the image buildah will produce.
      name: IMAGE
      type: string
    - name: prnumber
      description: In case of PR, PR number that is to be used in image tag. If this field is empty it means that it's a commit on main branch
      default: "NA"
    - name: gitrepositoryurl
      description: The git repository url
    - name: tekton-bot
      description: Name of the secret that contains token to talk to the api.
      default: "github-stakater-tekton-bot"
  steps:
    - name: comment-on-pr
      image: stakater/pipeline-toolbox:v0.0.20
      command: ["/bin/bash"]
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: $params.tekton-bot
              key: password
      args:
        - -c
        - |
          if [ $(params.prnumber) != "NA" ]; then
            REPO_URL=$(params.gitrepositoryurl)
            REPO_NAME=${REPO_URL#*$".com"} 
            REPO_NAME=${REPO_NAME:1}
            curl -s -H "Authorization: token ${GITHUBTOKEN}" \
            -X POST -d '{"body": "Tekton - Pipeline ran successfully and image `$(params.IMAGE)` is available"}' \
            "https://api.github.com/repos/${REPO_NAME}/issues/$(params.prnumber)/comments"
          else
            echo "Not a PR so cant comment"
          fi
