apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: {{ include "ct.name" . }}
spec:
  steps:
    - image: 'maven:3.8.6-openjdk-11-slim'
      name: test
      script: |
        mvn clean test
      workingDir: $(workspaces.source.path)
      when:
        - input: "$(workspaces.source.path)/*.xml"
          operator: in
          values: ["yes"]
    - name: test
      image: mcr.microsoft.com/dotnet/sdk:6.0
      script: |
        #!/usr/bin/env sh
        set -e
        dotnet restore
        dotnet build
        ls *Tests*/*.csproj | while read -r file;
            do dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover "${file}";
        done
      workingDir: $(workspaces.source.path)
      when:
        - input: "$(workspaces.source.path)/*.sln"
          operator: in
          values: ["yes"]
  workspaces:
    - name: source
    
