apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: {{ include "ct.name" . }}
spec:
  steps:
    - image: 'maven:3.6.3-openjdk-11-slim'
      name: test
      resources: {}
      script: |
        if [ -f "pom.xml" ]
        then
         mvn clean test
        else
         echo "No maven project found"
        fi
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
