apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: {{ include "ct.name" . }}
spec:
  steps:
    - image: 'maven:3.8.6-openjdk-11-slim'
      name: test
      script: |
        mvn clean test
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
    
