apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: {{ include "stakater-validate-environment.name" . }}
  annotations:
    description: |
      Validate HelmRelease Status of Tronodor Environment
spec:
  workspaces:
  - name: source
  params:
    - name: ENVIRONMENT_NAME
      description: Time in seconds to wait for environment
      default: ""
    - name: WAIT_TIME_FOR_RECONCILE
      description: Time in seconds to wait for environment
      default: "120"
    - name: RETRY_INTERVAL
      description: Time in seconds to get environment and check statuses
      default: "5"
  steps:
  - name: validate-environment
    image: stakater/pipeline-toolbox:v0.0.20
    command: ["/bin/bash"]
    workingDir: $(workspaces.source.path)
    args:
      - -c
      - |
        if [ $(params.ENVIRONMENT_NAME) != "" ]; then
          # Get Environment from task param
          environment_name="$(params.ENVIRONMENT_NAME)"
        else
          # Get Environment Name from environment file generated by create environment task
          environment_name=$(yq .metadata.name $(workspaces.source.path)/environment/environment.yaml )
        fi
        echo "Checking Environment $environment_name"

        # Wait Until Timeout
        for (( t=1; t < $(params.WAIT_TIME_FOR_RECONCILE); t++ ))
        do
          # Get Environment Status
          environment_status=$(oc get environment $environment_name -o jsonpath='{.status}')

          # Get Fields to check Environment Reconcilation
          condition_type=$(echo $environment_status | jq -r '.resourceStatus.conditions[0].type')
          condition_status=$(echo $environment_status | jq -r '.resourceStatus.conditions[0].status')

          # Check Environment Reconcilation
          if ([ $condition_type == "ReconcileSuccess" ] && [ $condition_status == "True" ]); then
            echo "--Environment Reconciled"
            echo "  Checking HelmRelease"

            # Get Fields to check HelmRelease status
            helmrelease_type=$(echo $environment_status | jq -r '.helmReleaseStatus.latestCondition.type')
            helmrelease_status=$(echo $environment_status | jq -r '.helmReleaseStatus.latestCondition.status')
            #echo "  HelmReleaseStatus:$helmrelease_status"
            #echo "  HelmRelease_type:$helmrelease_type"

            # Check HelmRelease status
            if ([ $helmrelease_type == "Released" ] && [ $helmrelease_status == "True" ]); then
              echo "---HelmRelease succesful"
              echo "   Status:" "$helmrelease_status"
              echo "   Type:" "$helmrelease_type"
              echo "   Message" "$(echo $environment_status | jq  '.helmReleaseStatus.latestCondition.message')"
              echo "   Reason" "$(echo $environment_status | jq  '.helmReleaseStatus.latestCondition.reason')"
              break
            else
              echo "---HelmRelease Unsuccesful"
              echo "   Status:" "$helmrelease_status"
              echo "   Type:" "$helmreleaseType"
              echo "   Message" "$(echo $environment_status | jq  '.helmReleaseStatus.latestCondition.message')"
              echo "   Reason" "$(echo $environment_status | jq  '.helmReleaseStatus.latestCondition.reason')"
          fi
          else
            echo " Environment Not Reconciled"
          fi

          sleep $(params.RETRY_INTERVAL) && echo ""
        done
