apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: {{ include "cluster-task.name" . }}
spec:
  steps:
    - image: 'maven:3.8.6-openjdk-11-slim'
      name: code-lint
      script: |
        if [ -f "pom.xml" ]
        then
         mvn checkstyle:check
        else
         echo "No maven project found"
        fi
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
