name: Render Helm Chart and Change kind from Clustertask to Task

on:
  workflow_call:
    inputs:
      NEXT_VERSION:
        required: true
        type: string

      SUBPATH:
        required: true
        type: string

jobs:
  render_and_replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
         version: v3.7.0

      - name: Render Helm Chart
        run: |
          helm template test-chart ${{ inputs.SUBPATH }}/helm  > task-${{ inputs.NEXT_VERSION }}.yaml

      - name: Create Directory
        run: mkdir -p ${{ inputs.SUBPATH }}/rendered

      - name: Move Rendered Chart
        run: mv task-${{ inputs.NEXT_VERSION }}.yaml ${{ inputs.SUBPATH }}/rendered

      - name: Replace Word in Rendered File
        run: |
          sed -i 's/ClusterTask/Task/g' ${{ inputs.SUBPATH }}/rendered/task-${{ inputs.NEXT_VERSION }}.yaml

      - name: Commit Changes
        run: |
          git config --local user.email "github-root@stakater.com"
          git config --local user.name "stakater-github-root"
          git add ${{ inputs.SUBPATH }}/rendered
          git commit -m "Add rendered and modified Helm chart"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.STAKATER_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
