name: Render Helm Chart and Change kind from Clustertask to Task

on:
  workflow_call:
    concurrency: tekton
    inputs:
      NEXT_VERSION:
        required: true
        type: string

      SUBPATH:
        required: true
        type: string

    secrets:
      STAKATER_GITHUB_TOKEN:
        description: "Token for pushing code"
        required: true
jobs:
  render_and_replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.STAKATER_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
         version: v3.7.0

      - name: Render Helm Chart
        run: |
          helm template test-chart ${{ inputs.SUBPATH }}/helm  > ${{ inputs.SUBPATH }}-${{ inputs.NEXT_VERSION }}.yaml

      - name: Create Directory
        run: mkdir -p ${{ inputs.SUBPATH }}/rendered

      - name: Move Rendered Chart
        run: mv ${{ inputs.SUBPATH }}-${{ inputs.NEXT_VERSION }}.yaml ${{ inputs.SUBPATH }}/rendered

      - name: Replace Word in Rendered File
        run: |
          sed -i 's/ClusterTask/Task/g' ${{ inputs.SUBPATH }}/rendered/${{ inputs.SUBPATH }}-${{ inputs.NEXT_VERSION }}.yaml
          sed -i -E 's/${{ inputs.SUBPATH }}-[0-9]+\.[0-9]+\.[0-9]+/${{ inputs.SUBPATH }}-${{ inputs.NEXT_VERSION }}/g' ${{ inputs.SUBPATH }}/rendered/${{ inputs.SUBPATH }}-${{ inputs.NEXT_VERSION }}.yaml

      - name: Commit Changes
        run: |
          git config --global user.email "stakater@gmail.com"
          git config --global user.name "stakater-user"
          git add ${{ inputs.SUBPATH }}/rendered
          git commit -m "[skip ci] Add rendered and modified Helm chart"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.STAKATER_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
