name: stakater-set-commit-status cluster task Helm Chart
on:
  pull_request:
    branches:
    - main
    paths:
    - 'stakater-set-commit-status/**'

  push:
    branches:
    - main
    paths:
    - 'stakater-set-commit-status/**'
    - '.github/workflows/stakater_set_commit_status.yaml'


jobs:
  clustertask-test-run:
    name: ClusterTask Test Run on SNO
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.sha}}

    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"

    # This is used to setup kubeconfig, required by Tilt
    - name: Login to cluster
      run: oc login --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) --server=https://kubernetes.default.svc --insecure-skip-tls-verify=true

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.2

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.26.0

    - name: Install tilt
      run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash

    - name: Tilt up
      run: tilt ci -f stakater-set-commit-status/tests/Til --timeout 5m0s

    - name: Tilt down
      if: always()
      run: tilt down --delete-namespaces --file ./Tiltfile-delete

  next-version:
    uses: stakater/tekton-catalog/.github/workflows/next_version.yaml@main
    with:
      component: stakater-set-commit-status

  pull-request:
    uses: stakater/tekton-catalog/.github/workflows/pull_request.yaml@main
    name: Pull Request
    if: ${{ github.ref != 'refs/heads/main' }}
    needs:
    - next-version
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    with:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      HELM_REGISTRY_URL: oci://ghcr.io/stakater/charts
      SUBPATH: stakater-set-commit-status
      PUSH_CONTAINER_IMAGE: ${{ needs.next-version.outputs.dockerfile_exists }}
      PUBLISH_HEM_CHART: ${{ needs.next-version.outputs.helm_chart_exists }}
      NEXT_VERSION: ${{ needs.next-version.outputs.version }}

  push-and-release:
    uses: stakater/tekton-catalog/.github/workflows/push.yaml@main
    name: Push and Release
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
    - next-version
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    with:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      HELM_REGISTRY_URL: oci://ghcr.io/stakater/charts
      SUBPATH: stakater-set-commit-status
      PUSH_CONTAINER_IMAGE: ${{ needs.next-version.outputs.dockerfile_exists }}
      PUBLISH_HEM_CHART: ${{ needs.next-version.outputs.helm_chart_exists }}
      NEXT_VERSION: ${{ needs.next-version.outputs.version }}